### ISSUE TITLE
Protótipo de tela

### ISSUE THREAD

**Issue by dbernardos** [dbernardos/KATOOH#1]

**Comment by Megwazi** [comment]
**Logo do Katooh** 

Conceito criado visando demonstrar visualmente o propósito de perguntas _(interrogações brancas no K)_ e as respostas _(exclamação na parte esquerda)_ utilizando a parte direita da letra K na cor verde, simulando assim um sinal de correto.

![Image](https://github.com/dbernardos/KATOOH/assets/116983819/ff4c840e-8b1e-4c2c-8430-b6d36590f8e3)
